### ISSUE TITLE
[Docs] Add more content on README

### ISSUE THREAD

**Issue by dscyrescotti** [dscyrescotti/Memola#76]
### Description
This is a call to add more details on README as follows:
- [x] To explain project set up
- [x] To elaborate on contribution
- [x] To include tech stack

**Comment by that-ar-guy** [comment]
hi @dscyrescotti  can i take this up

**Comment by dscyrescotti** [comment]
@that-ar-guy Thank you for your effort! I'm afraid that I've already updated README along with contribution guidelines. However, if you are really interested in working on documentation, you can review the following docs:
- [README.md](https://github.com/dscyrescotti/Memola/blob/main/README.md)
- [CONTRIBUTING.md](https://github.com/dscyrescotti/Memola/blob/main/CONTRIBUTING.md)

Feel free to suggest anything you want to elaborate on. Much appreciated!
